### PR TITLE
docs: Add Ben as first contributor

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
@all-contributors
please add @benkrikler for code, doc.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @benkrikler for code, doc.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @jpivarski for maintenance, data, doc.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @henryiii for maintenance, data, code, doc.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @eduardo-rodrigues for maintenance, data, code.

**Comment by jpivarski** [comment]
@eduardo-rodrigues, if you haven't already encountered this problem, launching multiple all-contributors requests from the same branch (radiating pattern) makes it difficult to merge them in the end. I've found it much easier to launch each from `main` after the previous is fully merged into `main` (linear, sequential pattern).

Ah, but maybe that's what you're doing; there are many minutes between each all-contributors bot. If that's what you're already doing, go ahead and ignore this comment. Otherwise, it's a heads-up.

**Comment by eduardo-rodrigues** [comment]
Thanks @jpivarski. I did encounter that problem when I introduced all-contributions in DecayLanguage, which was my first experience with the tools. I then had to leard and manually fix things the hard way.

Here I'm profiting from the fact that the bot picks a request up even in a merged MR and all goes fine if I add people one-by-one since the MRs are created from master. I do need to merge them also as I go along.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @reikdas for data, code.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @Moelf for data, code.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @jonas-eschle for code.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @kratsg for data, code.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @veprbl for data.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @HealthyPear for data.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @lobis for data.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @oshadura for data.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @nsmith- for data.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @8me for data.

**Pull request merged**
