### PR TITLE
chore: Update pre-commit hooks and add Python 3.10 to PyPI metadata

### PR DESCRIPTION
**Pull request by matthewfeickert**
PR #68 bumped CI to add Python 3.10 and that is passing, so we can now add support for Python 3.10 to the PyPI metadata.

**Suggested squash and merge commit message**:
```
* Update pre-commit hooks
* Add pre-commit.ci config for quarterly updates
* Add types-PyYAML and types-requests dependencies to mypy pre-commit hook
* Remove mypy 2.7 pre-commit hook
* Apply pre-commit hooks to update setup.cfg
* Add pre-commit.ci badge to README
```

### CODE REVIEW

**Comment by henryiii** [comment]
setup-cfg-fmt should be doing this for us? Is it not set up or not being updated in pre-commit.ci?

**Comment by matthewfeickert** [comment]
> setup-cfg-fmt should be doing this for us? Is it not set up or not being updated in pre-commit.ci?

Apparently `pre-commit.ci` isn't running?

I guess I need to go look at how setup-cfg-fmt works as when I ran `pre-commit run --all-files` locally it just undid this commit

```diff
$ git diff
diff --git a/dev/make-root/rntuple_int_float.C b/dev/make-root/rntuple_int_float.C
index 5b12c95..bdbd669 100644
--- a/dev/make-root/rntuple_int_float.C
+++ b/dev/make-root/rntuple_int_float.C
@@ -53,4 +53,4 @@ void rntuple_int_float() {
   *int_field = 0;
   *float_field = 0.0;
   ntuple->Fill();
-}
\ No newline at end of file
+}
diff --git a/setup.cfg b/setup.cfg
index 4269385..8bb4a02 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -23,7 +23,6 @@ classifiers =
     Programming Language :: Python :: 3.7
     Programming Language :: Python :: 3.8
     Programming Language :: Python :: 3.9
-    Programming Language :: Python :: 3.10
     Typing :: Typed
 keywords =
     ROOT
```

**Comment by matthewfeickert** [comment]
Just added `scikit-hep-testdata` to pre-commit.ci and reran.

**Comment by matthewfeickert** [comment]
I'll have to come back to this later as I'm not sure how to resolve the issues with `mypy 2.7`

```
mypy 2.7.................................................................Failed
- hook id: mypy
- exit code: 1

src/skhep_testdata/remote_files.py:10: error: Library stubs not installed for "yaml" (or incompatible with Python 2.7)
src/skhep_testdata/remote_files.py:10: note: Hint: "python3 -m pip install types-PyYAML"
src/skhep_testdata/local_files.py:10: error: Library stubs not installed for "requests" (or incompatible with Python 2.7)
src/skhep_testdata/local_files.py:10: note: Hint: "python3 -m pip install types-requests"
src/skhep_testdata/local_files.py:10: note: (or run "mypy --install-types" to install all missing stub packages)
src/skhep_testdata/local_files.py:10: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/skhep_testdata/local_files.py:15: error: Library stubs not installed for "pathlib2" (or incompatible with Python 2.7)
src/skhep_testdata/local_files.py:15: note: Hint: "python3 -m pip install types-pathlib2"
Found 3 errors in 2 files (checked 5 source files)
```

as `types-PyYAML` and `types-requests` are Python 3 only.

**Comment by henryiii** [comment]
We are dumping Python 2 Jan 1, 2022. You can remove the MyPy python 2 check now for all I care.

I'd be perfectly happy to dump Python 2 now across all of Scikit-HEP if you can get @jpivarski (uproot 4) and @eduardo-rodrigues (Particle, hepunits) to agree. ;) As long as we bump python_requires, Python 2 will still work it will just be frozen to old versions going forward, but it already is a frozen version itself. Given this is needed for testing at least uproot, it needs to drop it after those do.

**Comment by jpivarski** [comment]
I'd like to do one last version of Awkward and Uproot with Python 2 and then bump the minor number, so it's easier to keep track of which one is the first Python 3-only. When is that needed? Can it be after Thanksgiving?

**Comment by henryiii** [comment]
I'm not really available till Dec 8 or after, so I hope so! :)

Bumming at least the minor version numbers is important, so it's easy to backport fixes if you really have to.

**Comment by matthewfeickert** [comment]
> We are dumping Python 2 Jan 1, 2022. You can remove the MyPy python 2 check now for all I care.

Done. :+1: CI is passing now so ready for review.

**Review by jpivarski — APPROVED** [review]
Looks good to me.

**Comment by matthewfeickert** [comment]
> Looks good to me.

Cool. :) I'm going to release `v0.4.11` from this PR so that `pyhf` can use it.

**Pull request merged**
