### PR TITLE
feat: add uproot ntuple 6.29/01 files

### PR DESCRIPTION
**Pull request by ioanaif**
Files used in uproot PR [962](https://github.com/scikit-hep/uproot5/pull/962) ; taken from UnROOT PR [262](https://github.com/JuliaHEP/UnROOT.jl/pull/264)

### CODE REVIEW

**Comment by Moelf** [comment]
I think you also want to include the original `.C` source files maybe?

**Comment by ioanaif** [comment]
I don't believe it's needed for `uproot` testing; I was thinking if someone needs to check it, they can do so through the UnROOT PR.

**Comment by Moelf** [comment]
https://github.com/scikit-hep/scikit-hep-testdata/blob/main/dev/make-root/rntuple_int_multicluster.C

I try to keep them anyway xD

**Comment by jpivarski** [comment]
Keeping the .C files is better, since it makes it easier to produce new ROOT files when the RNTuple format changes again. So if you have them, please do add them.

**Comment by ioanaif** [comment]
Ah, I didn't know about the /dev/make-root part. 

Then they were already previously added, as I didn't change anything to the .C files. 

However, the test files that are already in scikit-hep-testdata, are not the ones used in https://github.com/JuliaHEP/UnROOT.jl/pull/264. 

The files were added in January https://github.com/scikit-hep/scikit-hep-testdata/pull/111 and the update was done in https://github.com/JuliaHEP/UnROOT.jl/pull/264

**Review by jpivarski — APPROVED** [review]
Okay, if the .C files weren't changed and there's now a reference here connecting the ROOT file with them, then that's all that's needed for posterity. I'll merge this and make a new release.

**Comment by Moelf** [comment]
what I intended to do (and what I do for UnROOT.jl) is that I will refresh/replace the `.root` file when there's a new ROOT breaking change release, until they hit stable release

**Pull request merged**
