### PR TITLE
feat: add more RNTuple files

### PR DESCRIPTION
**Pull request by ariostas**
I added three more RNTuple files that have been useful to test and debug uproot. These files were created and used by @Moelf for UnROOT testing, and can be found [here](https://github.com/JuliaHEP/UnROOT.jl/tree/main/test/samples/RNTuple).

### CODE REVIEW

**Comment by Moelf** [comment]
it may be a good idea to copy the source code to https://github.com/scikit-hep/scikit-hep-testdata/tree/main/dev/make-root and generate yourself to make sure!

**Comment by ariostas** [comment]
Thanks @Moelf! For `Run2012BC_DoubleMuParked_Muons_rntuple_1000evts.root` I couldn't find the original `Run2012BC_DoubleMuParked_Muons.root` file in the UnROOT repo. For `test_ntuple_extension_columns.root`, I don't have access to a raw ATLAS file. And I'm not sure how `DAOD_TRUTH3_RC2.root` was generated.

**Comment by ariostas** [comment]
> For Run2012BC_DoubleMuParked_Muons_rntuple_1000evts.root I couldn't find the original Run2012BC_DoubleMuParked_Muons.root file in the UnROOT repo.

Sorry, I just realized that that's a public file.

**Comment by Moelf** [comment]
oh you're right... yeah those files are a bit cryptic, indeed I had to produce them with ATLAS stuff.

**Comment by ariostas** [comment]
I added partial instructions for how to generate these files, like in the UnROOT repo.

I'll look into writing some script to generate similar test files without having to use any ATLAS tools.

**Comment by ariostas** [comment]
@jpivarski seems like I can't request a reviewer since I'm not a member of this repo (or scikit-hep), but this is ready for review now.

**Review by jpivarski — APPROVED** [review]

**Comment by jpivarski** [comment]
It's ready: https://pypi.org/project/scikit-hep-testdata/0.4.44/

**Pull request merged**
