### PR TITLE
update RNTuple using ROOT 6.26/04

### PR DESCRIPTION
**Pull request by Moelf**
@jpivarski

### CODE REVIEW

**Comment by jpivarski** [comment]
This looks like a draft. When it's done, I'll make sure the final .root files make it into a release so that the Uproot CI can just pull a scikit-hep-testdata from PyPI.

**Comment by Moelf** [comment]
As it is it fixs the only RNTuple we have, but I guess we can wait until I add the new ones as well, will reuse this PR

**Comment by jpivarski** [comment]
I missed the fact that the .root file itself has changed. Well, that's enough for now. (I thought this PR had no .root file at all.)

I'll merge it and get it into a release.

**Comment by jpivarski** [comment]
(Uproot isn't already using this file, so it won't break any tests.)

**Pull request merged**
