### PR TITLE
These files demonstrate issues that I was too busy to deal with in Uproot3 but should look at for Uproot4.

### PR DESCRIPTION
**Pull request by jpivarski**
I'll eventually want them in a new release. I'm at least a week away from that; just submitting early.

Thanks!

### CODE REVIEW

**Comment by jpivarski** [comment]
@benkrikler and @henryiii, is there any reason to have both GHA and Travis? The Travis is failing because it's misconfigured (missing `pytest_cov`):

```
Plugin 'pytest_cov' could not be loaded: (pytest 4.3.1 (/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages)
```

in Python 2.7 and

```
pkg_resources.VersionConflict: (pytest 4.3.1 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('pytest>=4.6'))
luggy.manager.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (pytest 4.3.1 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('pytest>=4.6'))!
```

If just dropping the `.travis.yml` is an option, I'll do that.

**Comment by eduardo-rodrigues** [comment]
@jpivarski, yes, it's pretty clear that a single CI should be up and running. Just go ahead and remove Travis at this stage ...

**Comment by henryiii** [comment]
Most cases where Travis is still around is because of coverage - I've never bothered to properly move coverage over to Azure or GHA. I don't think it's really even that important for a test data repo. But that's usually why.

**Comment by jpivarski** [comment]
After merging this PR, I'll attempt to deploy a new version by just tagging with a new number. It will be interesting to see if that works.

(And it would be worth adopting into Uproot4 if it does; Awkward1 is a bit too complicated with synchronizing the Python package with the C++ libraries, and now awkward1-cuda-kernels is going to be a separate package with the same version numbers, so it can be included as an "extras" dependency. But Uproot4 is simple enough that I think it would be a nice addition.)

**Comment by henryiii** [comment]
Tags should always start with a v, GitHub suggests this in the right-hand side - please delete the release and tag and rerelease.

**Comment by jpivarski** [comment]
Thanks! I just noticed that and that's what I was doing.

**Comment by henryiii** [comment]
Much better. :)

**Comment by jpivarski** [comment]
Agreed: the CI just triggered...

**Comment by jpivarski** [comment]
Darn; we've exceeded the 60 MB limit. Now the hard choices begin.

**Comment by henryiii** [comment]
> File too large. Limit for project 'scikit-hep-testdata' is 60 MB

We need to come up with a new system if we can't get the PyPI file size increased. I think we should probably host these somewhere and download them using the package.

**Comment by jpivarski** [comment]
If so, then the repo should probably be heavily rebased or replaced, since it's slow to git clone because of the large files in its history. I'm sure we could host the files somewhere comfortably, but the download would have to be automatic because knowing that you have local files is a big plus for CI (all the tests except the ones that explicitly test networking). The main problems with Uproot3 tests is that some of the files (the big ones) are remote. They often fail for connection issues.

**Comment by eduardo-rodrigues** [comment]
This issue of package size comes up again. I have requested an increase with PyPI but they seem to be taking a lot of time to respond, see https://github.com/pypa/pypi-support/issues/382 from mid May …

There are related discussions in https://github.com/scikit-hep/scikit-hep-testdata/issues/16 and https://github.com/scikit-hep/scikit-hep-testdata/issues/30.

**Comment by henryiii** [comment]
The repo could still have the files - you would just not add them to the wheel/SDist. Maybe you could even download them from there. But yes, it would be better to replace or rewrite history, and host the files somewhere else completely. The files don't change, they just get added onto.

**Comment by jpivarski** [comment]
Does the limit not apply to source tarballs? If so, then that would be perfect—this package is unspecialized pure Python, so it doesn't need to be a wheel. (I'm doing that in Uproot, too: there are no extension modules/one package works for all systems, so I'm distributing it as source only.)

**Comment by eduardo-rodrigues** [comment]
I believe the limit applies to all files, either source or wheel, but only after compression.

**Comment by henryiii** [comment]
We do not provide the SDist for Scikit-HEP test data, since the wheel is superior. Please do not *just* distribute the SDist, even for pure Python universal wheels!!! The wheel *does not run arbitrary executable code* when it installs, while the SDist does. It is both faster and safer. I think it is better to just distribute the wheel if you really have to chose one (though that is only for cases like this, where both are large).

For example, see https://pythonwheels.com, which tracks *all* packages, not just binaries. Wheels are better than SDists, even if you have pure Python.

**Comment by henryiii** [comment]
Here are the advantages for pure Python, taken from the page above:

1. Faster installation for pure Python ~~and native C extension packages.~~
2. Avoids arbitrary code execution for installation. (Avoids setup.py)
3. ~~Installation of a C extension does not require a compiler on Linux, Windows or macOS.~~
4. Allows better caching for testing and continuous integration.
5. Creates .pyc files as part of installation to ensure they match the Python interpreter used.
6. More consistent installs across platforms and machines.

Note that 5 should also mean that you have more consistent runtimes - the first run of you package does not have to cache all the .pyc files, they are created at install time (that's also why the install might not be as much faster than a SDist install that you would expect).

Also, you can use newer technologies in your setup.py than the user has access to with Pip/Setuptools, and the wheel will still run because it does not run setup.py when installing.

And PEP 518 is *way* faster as a wheel, as it only changes the creation of the wheel, even for pure Python.

**Comment by jpivarski** [comment]
Okay, I didn't know about those advantages. Since we're the authors of the setup.pys and can refrain from putting bad stuff in there, I take it that the main advantages for us are that wheels generate .pyc at install time and (since they're artifacts, not scripts) caching in CI.

**Comment by henryiii** [comment]
Also faster installs, since running setup.py and setuptools takes time (ignoring the caching time, since that happens somewhere, either at runtime or install time). And it's not "bad stuff" - using the latest goodies in your setup.py makes it nicer and reduces certain types of issues and code bloat. If you provide wheels, you don't have to bother users to also have the latest goodies. :)

**Pull request merged**
