### PR TITLE
dev: Add python script for making the ROOT file with TEfficiency memberwise

### PR DESCRIPTION
**Pull request by kratsg**

### CODE REVIEW

**Comment by jpivarski** [comment]
@kratsg If you have permissions to merge this when you're done, I'd say you can go ahead and do so. The script used to generate the new ROOT files are "for informational purposes only" and won't break anybody's CI.

**Comment by kratsg** [comment]
> @kratsg If you have permissions to merge this when you're done, I'd say you can go ahead and do so. The script used to generate the new ROOT files are "for informational purposes only" and won't break anybody's CI.

I'll update `pytest` to skip `dev/` from being tested. Seems to be picked up. Then I'll go ahead and merge it in.

**Comment by eduardo-rodrigues** [comment]
@kratsg, out of curiosity why is the file named `uproot-issue38c.py` and not simply `uproot-issue38.py`? What's the "c" for?
You might as well have linked directly to the GitLab issue from the header of `uproot-issue38c.py`.

**Comment by kratsg** [comment]
> curiosity why is the file named `uproot-issue38c.py` and not simply `uproot-issue38.py`

there's `a` and `b` files that I didn't make. It's only making the file that I made with that script.

**Pull request merged**
