### PR TITLE
Add powheg-box-v2 lhe testfiles

### PR DESCRIPTION
**Pull request by APN-Pucky**
LHE files for several POWHEG-BOX-V2 processes https://powhegbox.mib.infn.it/ (process details are in the papers for specific process listed on their webpage)

The specific powheg run parameter are included in the beginning comment of the lhe files and correspond to the testrun configurations provided with the powheg box code.

This does not include all processes available, but only a descriptive subset of different setups and processes:

- pylhe-testfile-powheg-box-v2-W.lhe - W NLO production process
- pylhe-testfile-powheg-box-v2-Z.lhe - Z NLO production process
- pylhe-testfile-powheg-box-v2-Zj.lhe - Z+j NLO production process
- pylhe-testfile-powheg-box-v2-directphoton.lhe - gamma+j NLO production process
- pylhe-testfile-powheg-box-v2-hvq.lhe - open heavy quark NLO production process
- pylhe-testfile-powheg-box-v2-trijet.lhe - j+j+j NLO production process

For https://github.com/scikit-hep/pylhe/pull/220

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi. For reference can you edit the top-level box to explain what the various files are? This is useful for the future.

This is a very useful addition and we should merge and release. WDYT @jpivarski?

**Review by eduardo-rodrigues — APPROVED** [review]

**Comment by APN-Pucky** [comment]
oh, yes that makes sense. Done.

**Comment by eduardo-rodrigues** [comment]
@all-contributors please add @APN-Pucky for data.

**Comment by jpivarski** [comment]
You already merged it, but yes this is good.

**Comment by eduardo-rodrigues** [comment]
Thanks and sorry for the rush, Jim. It was a crazy day and I acted where I could when I had a bit of time. Dunno if you have anything else in the pipeline or if you would be happy to make a new release to finalise the enhancement in pylhe? Advance thanks.

**Comment by jpivarski** [comment]
I'm glad you went ahead without waiting for me. Adding a few kilobyte-sized files to support pylhe is definitely a good use of this repo.

**Comment by eduardo-rodrigues** [comment]
@jpivarski, I'm not sure if you've been doing anything special for the releases but I tagged https://github.com/scikit-hep/scikit-hep-testdata/releases/tag/v0.4.36 and it's not yet on PyPI after 5 minutes or so, which is strange.

**Comment by jpivarski** [comment]
You have to make a GitHub release to trigger PyPI deployment, not just a tag. When you make a GitHub release, you can use this existing tag, though.

**Comment by jpivarski** [comment]
You're right, and I was looking for this thread (on my phone) to follow up, but couldn't find it. I see the release, so it should have triggered. But also, I don't even see the GitHub Action for it in the actions tab or its definition in .github/workflows. I _know_ this has had a GitHub release-triggered deployment, because that's how I've always done it.

**Comment by eduardo-rodrigues** [comment]
Thanks for the check. Strange indeed.

In the meantime the conda release got done and merged, see https://github.com/conda-forge/scikit-hep-testdata-feedstock/pull/53.

**Comment by eduardo-rodrigues** [comment]
I decided to upload manually to PyPI to get this done.

**Pull request merged**
