### PR TITLE
These files bring scikit-hep-testfiles up to date with what's in Uproot.

### PR DESCRIPTION
**Pull request by jpivarski**
The intention is for the scikit-hep/uproot4 repo to contain zero test files and get them all from here for the testing phase. Thus, uproot4's test requirements includes scikit-hep-testfiles.

This is a pull request so that we can review the files before merging them into the master branch. I'm taking the README's 25 MB limit as a cutoff, although I really wouldn't upload any file that's more than 10 MB. (Maybe that's also a GitHub limit...)

### CODE REVIEW

**Comment by jpivarski** [comment]
These are the files I'd like to merge into a new version of scikit-hep-testdata.

I'd like this to become version 0.1.4 on conda-forge.

@benkrikler, @eduardo-rodrigues, @henryiii: who should I be talking to? Does somebody own this package? Thanks!

**Comment by henryiii** [comment]
@benkrikler I think. I just like making things work better. :)

**Comment by henryiii** [comment]
I believe there is a mechanism for downloading remote files, too (@benkrikler?)

**Comment by eduardo-rodrigues** [comment]
Indeed @benkrikler is the maintainer. But we're all responsible for the maintenance of our packages, to some extent …

This PR is a no-brainer, adding new test files. This is most welcome so good to be merged, clearly.

**Comment by jpivarski** [comment]
Great, thanks! It's something that I've been meaning to do for a while. I can finally archive it from my inbox.

**Comment by eduardo-rodrigues** [comment]
Yes, a new version makes sense. @henryiii, did you manually make the previous release? Or else via …? Manually is not complicated in any case.

**Comment by jpivarski** [comment]
By "manually," do you mean I should create a GitHub release with a new version number? Would that trigger the PyPI deployment with that version number?

**Pull request merged**
