### PR TITLE
Adding a place for scripts that make ROOT files with specific types of data.

### PR DESCRIPTION
**Pull request by jpivarski**
sample4version.C is a script used to make identical ROOT files across 11 years of ROOT versions (differing only by ROOT version and chosen compression method, though in practice hardly any of the branches are actually compressed).

I'm also adding scripts to make various STL containers so that the test coverage is not limited by the files that users provide.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi @jpivarski, @henryiii, as you can see from https://github.com/pypa/pypi-support/issues/382 the PyPI support team kindly increased the size limit for us. 120 MB will make a difference!

@jpivarski, you can roll back on the removal of a few files to make our life far easier ...

**Comment by eduardo-rodrigues** [comment]
I mean cf. https://github.com/scikit-hep/scikit-hep-testdata/pull/34 and the discussions at https://github.com/scikit-hep/scikit-hep-testdata/pull/33.

**Comment by jpivarski** [comment]
This is great! It will be a long time before we get to 120 MB at our current rate, so this is a good solution. (And I'm sure from PyPI's perspective, a 120 MB cutoff serves the same function as a 60 MB cutoff.)

I'll put the three large files back in after this STL collections file.

**Comment by jpivarski** [comment]
This is a good test file.

**Pull request merged**
