### PR TITLE
Add manifest

### PR DESCRIPTION
**Pull request by mayou36**
@benkrikler good idea, I am not sure though if it works fully with the manifest yet, I'm testing

### CODE REVIEW

**Comment by mayou36** [comment]
This adds the data directly to the package.

Ready to merge from my side @benkrikler

**Comment by eduardo-rodrigues** [comment]
Note that you can also add data to the package, when distributed, without a MANIFEST.in file, see what I did in the `setup.py` file of https://github.com/scikit-hep/particle.

**Comment by mayou36** [comment]
Yes, TBO I don't know of any good argument for one or the other way, do you?

`package_data` looks more like made for it, though MANIFEST seems easier to read for me.

**Comment by eduardo-rodrigues** [comment]
Nope, I also do not know of strong arguments for one option or the other. Having the MANIFEST.in file can be easier to read, actually, if the files to include are more than just all in one directory, as in my case.
I commented for completeness. But fine by me what you did.

BTW, did you check that everything works as expected, to avoid surprises? You can just run `python setup.py sdist` locally, inspect the zip file created under `dist/`, and be reassured … I say this because I have had surprises, which I could have avoided had I been maniac with this trivial check :-).

**Comment by eduardo-rodrigues** [comment]
BTW, our of curiosity: you are starting to contribute to this package because you are using some of the test files? Just trying to find out the users / use cases of this young package. Thanks.

**Comment by mayou36** [comment]
> You can just run `python setup.py sdist` locally, inspect the zip...

Yes, exactly what I did. I also already had this nasty surprises :) (and here I had a typo at first, so it was worth checking)

Usecase: yes, simply to test and trial/error the root-file loading implementation in [zfit](https://github.com/zfit/zfit) using uproot. I find it always easier to interactively play with a package (like uproot) and this is the clean way of using a ROOT file that's also reproducible/playable with by others (too often I used one of the laying-around-root-files).

Plus for unittests a must-have.

**Comment by benkrikler** [comment]
Thanks @mayou36!  This looks good to me, I'll merge this and then close #6, which should be addressed by this as well.

I'm not that familiar with this aspect of packaging in python, but my understanding of the MANIFEST approach was that it also gives you access to files outside the src of your package (eg the README or the LICENSE txts).  I was being lazy in #6 and just using `package_data` in the setup.py, so the fact we now use the MANIFEST approach seems better to me, unless I've misunderstood things.

That's great as well to read your usecase with this package. That's exactly the sort of thing I had in mind originally, unit testing and distribution of commonly useful ROOT (and other) files :)

Anyway, thanks again, I'm merging in...

**Comment by eduardo-rodrigues** [comment]
Indeed. @mayou36, you are more than welcome to contribute with other test files you may find useful … BTW, these do *not* need to be ROOT files. Really, any files for testing are what the package is for :-).

**Pull request merged**
