### PR TITLE
Adding GHA, fixing deploy

### PR DESCRIPTION
**Pull request by henryiii**
Adding GitHub Actions. This should also fix the deploy once we make a token and add the secret.

We can drop Travis if we add codecov to GHA.

### CODE REVIEW

**Comment by DumbMachine** [comment]
# [Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=h1) Report
> Merging [#28](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=desc) into [master](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/commit/9a0f6cc426e86d4227fbc52618ecc26c0db11d3b&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master      #28   +/-   ##
=======================================
  Coverage   73.33%   73.33%           
=======================================
  Files           4        4           
  Lines         120      120           
=======================================
  Hits           88       88           
  Misses         32       32           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=footer). Last update [9a0f6cc...2afa3de](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by DumbMachine** [comment]
# [Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=h1) Report
> Merging [#28](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=desc) into [master](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/commit/9a0f6cc426e86d4227fbc52618ecc26c0db11d3b&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master      #28   +/-   ##
=======================================
  Coverage   73.33%   73.33%           
=======================================
  Files           4        4           
  Lines         120      120           
=======================================
  Hits           88       88           
  Misses         32       32           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=footer). Last update [9a0f6cc...d311496](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by DumbMachine** [comment]
# [Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=h1) Report
> Merging [#28](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=desc) into [master](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/commit/9a0f6cc426e86d4227fbc52618ecc26c0db11d3b&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master      #28   +/-   ##
=======================================
  Coverage   73.33%   73.33%           
=======================================
  Files           4        4           
  Lines         120      120           
=======================================
  Hits           88       88           
  Misses         32       32           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=footer). Last update [9a0f6cc...3d6815b](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by henryiii** [comment]
Is there any reason to include an sdist too? It's a universal wheel, and about 50 MB each (wheel and sdist).

**Comment by DumbMachine** [comment]
# [Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=h1) Report
> Merging [#28](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=desc) into [master](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/commit/9a0f6cc426e86d4227fbc52618ecc26c0db11d3b&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master      #28   +/-   ##
=======================================
  Coverage   73.33%   73.33%           
=======================================
  Files           4        4           
  Lines         120      120           
=======================================
  Hits           88       88           
  Misses         32       32           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=footer). Last update [9a0f6cc...1d839ec](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by DumbMachine** [comment]
# [Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=h1) Report
> Merging [#28](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=desc) into [master](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/commit/9a0f6cc426e86d4227fbc52618ecc26c0db11d3b&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master      #28   +/-   ##
=======================================
  Coverage   73.33%   73.33%           
=======================================
  Files           4        4           
  Lines         120      120           
=======================================
  Hits           88       88           
  Misses         32       32           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=footer). Last update [9a0f6cc...b201a3c](https://codecov.io/gh/scikit-hep/scikit-hep-testdata/pull/28?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Pull request merged**
