### PR TITLE
feat: Add data files with memberwise objects

### PR DESCRIPTION
**Pull request by kratsg**
This adds two new data files. One is from an existing issue at scikit-hep/uproot4#209. The other I created for scikit-hep/uproot4#38.

The one I created for that issue has the following python code (unsure where to place in this repository):

```python
import ROOT

fp = ROOT.TFile.Open("uproot-issue38c.root", "RECREATE")

nbins = 11

h_den = ROOT.TH1F('h_den', 'h_den', nbins, 0, 100)
h_num = ROOT.TH1F('h_num', 'h_num', nbins, 0, 100)

for i in range(1, nbins):
    h_num.SetBinContent(i, 2**i)
    h_den.SetBinContent(i, 2**(i+1))

eff = ROOT.TEfficiency(h_num, h_den)
eff.SetName('TEfficiencyName')
eff.SetTitle('TEfficiencyTitle')

eff.SetBetaBinParameters(0, -1.0, -2.0)
for i in range(1, nbins):
    eff.SetBetaBinParameters(i, 2**i, 2**(i+1))

eff.SetBetaBinParameters(nbins, -1.0, -2.0)

h_den.Write()
h_num.Write()
eff.Write()
fp.Close()
```

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
> The one I created for that issue has the following python code (unsure where to place in this repository)

Hi @kratsg, may I suggest that you create a directory `src/skhep_testdata/scripts` and add there your generating code with a filename that matches the resulting ROOT file under `data`? If you also add a README to the `scripts` directory I reckon that we would be good. I'm sure there are other ways but this seems simple and clear to me.

**Comment by jpivarski** [comment]
> Hi @kratsg, may I suggest that you create a directory `src/skhep_testdata/scripts` and add there your generating code with a filename that matches the resulting ROOT file under `data`?

There's a directory called `dev/make-root` for that, though the name could be more generic. It's not under `src` because it's not part of the package that should be deployed—it was used to make it.

**Review by jpivarski — APPROVED** [review]
Anyway, I misunderstood from my email, thinking that this PR was the Uproot PR, and that I would have to do a careful review of it—that's why I waited until today. As it is, it's two files that are currently blocking the Uproot PR because they're needed to test it. So I think we should approve these right away and make a new version.

I'll do that unless anyone complains.

**Comment by eduardo-rodrigues** [comment]
> > Hi @kratsg, may I suggest that you create a directory `src/skhep_testdata/scripts` and add there your generating code with a filename that matches the resulting ROOT file under `data`?
> 
> There's a directory called `dev/make-root` for that, though the name could be more generic. It's not under `src` because it's not part of the package that should be deployed—it was used to make it.

Ah, indeed I missed it. Thanks. Sure,, go ahead.

**Comment by jpivarski** [comment]
I made the release, so [v0.3.11](https://github.com/scikit-hep/scikit-hep-testdata/releases/tag/v0.3.11) will be available soon with these new files.

**Pull request merged**
