### PR TITLE
add 10-event LHE file with non-standard PDG particle

### PR DESCRIPTION
**Pull request by tomeichlersmith**
This is a test file for making sure that the graph rendering of pylhe can be done even if the LHE file has a particle with a non-standard PDG ID.

https://github.com/scikit-hep/pylhe/pull/180

The file was generated the MadGraph5 and then manually trimmed down to 10 events so that it isn't too large.

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
This is small enough and exactly what scikit-hep-testdata is for.

I approve this, and if you (@tomeichlersmith) are done with this PR, I'll merge it and make a new scikit-hep-testdata release so that you can start using it in https://github.com/scikit-hep/pylhe/pull/180 CI.

**Comment by tomeichlersmith** [comment]
Yep, I'm done :+1:

**Comment by jpivarski** [comment]
https://github.com/scikit-hep/scikit-hep-testdata/actions/runs/3988922907

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @tomeichlersmith for data.

**Pull request merged**
