### PR TITLE
For scikit-hep/uproot4#407

### PR DESCRIPTION
**Pull request by veprbl**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi @veprbl, can you explain what you are trying to achieve here? You are deleting a ROOT file that already exists in the repo but (1) the MR title says "Add" and the added macro rather creates a test.root file.

Ping @jpivarski as this is related to uproot work and I may well be unaware of WIP.

**Comment by eduardo-rodrigues** [comment]
This is related to https://github.com/scikit-hep/uproot4/pull/407 so one needs to decide whether to keep the ROOT file presently in the repo and make the new one uproot4-issue407.root, or override it. In any case the creation of the file test.root does not seem appropriate.

**Comment by jpivarski** [comment]
Generally, I add ROOT files here for Uproot tests only if they can't be made on the fly. The script you added along with the file shows that it can be generated easily. If it were converted to PyROOT, it could be written inline in the Uproot tests and there wouldn't be a need for coordination between scikit-hep-testdata and Uproot.

However, the reason that I avoid it is because it's a hassle, and you've already gone through the hassle. At this point, the easiest thing to do would be to merge this PR, tag it as a new version of scikit-hep-testdata, and use it in the Uproot test. I'd be in favor of doing that. The ROOT file follows the correct naming convention.

**Comment by jpivarski** [comment]
@eduardo-rodrigues, this is going to sound terrible, but the naming convention that distinguishes between Uproot 3 test files and Uproot 4 test files is that in Uproot 3, there's nothing between the word "issue" and the number, whereas in Uproot 4, there's a hyphen. That's how the potentially conflicting issue numbers between the two repos are resolved.

Basically, the new convention is the convention I wish we had from the beginning. Eventually, it won't matter because Uproot 4 issue/PR numbers will exceed Uproot 3's, and Uproot 3 will recede into the past.

uproot-issue-407.root is the correct name for an Uproot 4 test of issue or PR 407.

**Comment by veprbl** [comment]
The test case heavily relies on using a custom class to write a non-TObject TDatime and I'm not sure how one can implement that in PyROOT. The part with TTree does not actually fail in the current uproot4, but is left to exercise the "strided_interpretation".

**Comment by jpivarski** [comment]
> custom class to write a non-TObject TDatime and I'm not sure how one can implement that in PyROOT

That's a good enough argument for me. Anything _can_ be done: you could put the C++ class definition in a string as an argument to `ROOT.Declare` and call the new function from PyROOT, but there's no reason to add all that complexity while this works.

@veprbl, do you sign off on this? If so, I'll merge it and get a new release of scikit-hep-testdata made so that you'll be able to reference the file in the Uproot test.

**Comment by eduardo-rodrigues** [comment]
> @eduardo-rodrigues, this is going to sound terrible, but the naming convention that distinguishes between Uproot 3 test files and Uproot 4 test files is that in Uproot 3, there's nothing between the word "issue" and the number, whereas in Uproot 4, there's a hyphen. That's how the potentially conflicting issue numbers between the two repos are resolved.
> 
> Basically, the new convention is the convention I wish we had from the beginning. Eventually, it won't matter because Uproot 4 issue/PR numbers will exceed Uproot 3's, and Uproot 3 will recede into the past.
> 
> uproot-issue-407.root is the correct name for an Uproot 4 test of issue or PR 407.

Thanks @jpivarski, I had not realised that. In the meantime @veprbl updated the original commits to follow all conventions, even in the macro, so all good.

(Apologies for the interjection on something related directly to your work but since I just got back from work, bumped into this, and assumed that many of us may be away, I thought I would act.)

**Comment by veprbl** [comment]
> > custom class to write a non-TObject TDatime and I'm not sure how one can implement that in PyROOT
> 
> That's a good enough argument for me. Anything _can_ be done: you could put the C++ class definition in a string as an argument to `ROOT.Declare` and call the new function from PyROOT, but there's no reason to add all that complexity while this works.

Thanks for the hint, but it seems like that would not be enough:

```
>>> import ROOT
>>> ROOT.gInterpreter.Declare("""class TFoo : public TObject {
... public:
...   TDatime d;
... ClassDef(TFoo, 1);
... };""")
True
>>> foo = ROOT.TFoo()
>>> f = ROOT.TFile("/tmp/uproot-issue-407.root", "RECREATE")
>>> foo.Write("foo")
Error in <Streamer>: Cannot stream interpreted class.
36
```

> @veprbl, do you sign off on this? If so, I'll merge it and get a new release of scikit-hep-testdata made so that you'll be able to reference the file in the Uproot test.

It's a small file, so I would sign off on just adding it.

**Comment by jpivarski** [comment]
@eduardo-rodrigues Thanks for the vigilance! Overwriting `uproot-issue407.root` when `uproot-issue-407.root` was intended would have been bad.

**Comment by veprbl** [comment]
> @eduardo-rodrigues Thanks for the vigilance! Overwriting `uproot-issue407.root` when `uproot-issue-407.root` was intended would have been bad.

I second that. Nice catch, @eduardo-rodrigues

**Comment by jpivarski** [comment]
> `Error in <Streamer>: Cannot stream interpreted class.`

I guess I've never tried to serialize classes defined by Cling; I hadn't realized there would be this limitation. Okay, then it really couldn't have been done inline with PyROOT.

**Pull request merged**
